# -*- coding: utf-8 -*-
"""Ejercicio 18 examen .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18KKT79C9K7XwVmOHmCd9mN5ebIkxyq-K
"""

# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import adfuller, acf, pacf
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.stats.diagnostic import acorr_ljungbox
import warnings
warnings.filterwarnings("ignore")

# Step 1: Load and prepare the data
# Assuming the Excel file is uploaded to Colab
from google.colab import files
uploaded = files.upload()  # Upload '21.1.xlsx'

# Read the Excel file
data = pd.read_excel('21.1.xlsx')

# Extract the MONEY column and apply log transformation
data['log_MONEY'] = np.log(data['MONEY'])

# Plot the log-transformed series
plt.figure(figsize=(10, 6))
plt.plot(data['TIME'], data['log_MONEY'])
plt.title('Log-Transformed M1 Money Supply')
plt.xlabel('Time (Months from Jan 1951)')
plt.ylabel('Log(M1, Billions $)')
plt.show()

# Step 2: Check stationarity with ADF test
def adf_test(series, title=''):
    result = adfuller(series, autolag='AIC')
    print(f'ADF Test for {title}:')
    print(f'ADF Statistic: {result[0]:.4f}')
    print(f'p-value: {result[1]:.4f}')
    print(f'Critical Values: {result[4]}')
    print('Stationary' if result[1] < 0.05 else 'Non-Stationary')
    print()

adf_test(data['log_MONEY'], 'Log(M1)')

# Step 3: Difference the series to achieve stationarity
data['diff_log_MONEY'] = data['log_MONEY'].diff().dropna()
adf_test(data['diff_log_MONEY'].dropna(), 'First Difference of Log(M1)')

# Plot the differenced series
plt.figure(figsize=(10, 6))
plt.plot(data['TIME'][1:], data['diff_log_MONEY'][1:])
plt.title('First Difference of Log(M1)')
plt.xlabel('Time (Months from Jan 1951)')
plt.ylabel('ΔLog(M1)')
plt.show()

# Step 4: Plot ACF and PACF to identify p and q
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 4))
plot_acf(data['diff_log_MONEY'].dropna(), lags=20, ax=ax1)
plot_pacf(data['diff_log_MONEY'].dropna(), lags=20, ax=ax2)
ax1.set_title('ACF of First Difference')
ax2.set_title('PACF of First Difference')
plt.show()

# Step 5: Fit candidate ARIMA models
# Try ARIMA(1,1,1), ARIMA(1,1,0), ARIMA(0,1,1) based on typical patterns
models = [(1,1,1), (1,1,0), (0,1,1)]
results = []

for order in models:
    try:
        model = ARIMA(data['log_MONEY'], order=order)
        model_fit = model.fit()
        aic = model_fit.aic
        bic = model_fit.bic
        results.append((order, aic, bic))
        print(f'ARIMA{order} - AIC: {aic:.2f}, BIC: {bic:.2f}')

        # Diagnostics: Ljung-Box test for residuals
        residuals = model_fit.resid
        lb_test = acorr_ljungbox(residuals, lags=[10], return_df=True)
        print(f'Ljung-Box test (lag 10) p-value: {lb_test["lb_pvalue"].iloc[0]:.4f}')

        # Plot residuals
        plt.figure(figsize=(10, 6))
        plt.subplot(211)
        plt.plot(residuals)
        plt.title(f'Residuals of ARIMA{order}')
        plt.subplot(212)
        plot_acf(residuals, lags=20)
        plt.title('ACF of Residuals')
        plt.tight_layout()
        plt.show()
    except:
        print(f'ARIMA{order} failed to converge')

# Step 6: Select the best model based on AIC
best_model = min(results, key=lambda x: x[1])
print(f'Best Model: ARIMA{best_model[0]} with AIC: {best_model[1]:.2f}')

# Step 7: Fit the best model and forecast
best_order = best_model[0]
model = ARIMA(data['log_MONEY'], order=best_order)
model_fit = model.fit()

# Forecast 12 months ahead
forecast = model_fit.forecast(steps=12)
forecast_index = range(data['TIME'].iloc[-1] + 1, data['TIME'].iloc[-1] + 13)

# Exponentiate to get forecasts in original scale
forecast_orig = np.exp(forecast)

# Plot forecasts
plt.figure(figsize=(10, 6))
plt.plot(data['TIME'], data['MONEY'], label='Observed M1')
plt.plot(forecast_index, forecast_orig, label='Forecast M1', color='red')
plt.title(f'ARIMA{best_order} Forecast of M1 Money Supply')
plt.xlabel('Time (Months from Jan 1951)')
plt.ylabel('M1 (Billions $)')
plt.legend()
plt.show()

# Optional: Out-of-sample validation (use last 24 months as test set)
train = data['log_MONEY'][:-24]
test = data['log_MONEY'][-24:]
model = ARIMA(train, order=best_order)
model_fit = model.fit()
forecast_test = model_fit.forecast(steps=24)
mae = np.mean(np.abs(np.exp(forecast_test) - np.exp(test)))
print(f'Mean Absolute Error (MAE) on Test Set: {mae:.2f} Billions $')